# Generated by Django 3.1.7 on 2021-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatars/default_avatar.png', null=True, upload_to='users/avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
